/*SQL Structured Query Language*/

/*
SELECT
UPDATE
DELETE
INSERT INTO - INSERT NEW DATA IN TABLE
CREATE DATABASE
ALTER DATABASE - MODIFIS A DATABASE
CREATE TABLE
ALTER TABLE 
DROP TABLE - DETELE TABLE
CREATE INDEX - SECONDARY KEY FOR SEARCH
DROP INDEX
*/

SELECT DISTINCT /*TEKRARLARI YOK SAYAR*/

SELECT COUNT(DISTINCT Country) FROM Customers; /*UNIC OLACAK SEKILDE ULKELERI LISTELE*/

SELECT * FROM Customers WHERE CustomerId=1;

/*
= EQUAL 
> GRETTER THAN
< LESS THAN
>=, <=
<> OR !=
*/

SELECT * FROM Product WHERE Price BETWEEN 50 AND 60;

SELECT * FROM CUSTOMERS WHERE CITY LIKE 'sA'; /*San Fr, Salzburg*/

SELECT * FROM CUSTOMERS WHERE CITY IN ('PARIS', 'LONDON');

SELECT * FROM CUSTOMERS WHERE NOT COUNTRY='GERMANY' AND COUNTRY='USA';

SELECT * FROM CUSTOMERS WHERE COUNTRY='GERMANY' AND (CITY='BERLIN' OR CITY='MUNCHEN');
SELECT * FROM CUSTOMERS WHERE COUNTRY='GERNABY' AND CITY IN ('BERLIN', 'MUNCHEN');

SELECT * FROM CUSTOMERS ORDER BY CustomerId DESC; /*VARSAYILAN ESC YANI ARTAN*/



select * from Customers where CustomerId between 90 and 100 order by CustomerId desc;

select max(CustomerId) as a from Customers;
delete from Customers where Country is null;
